import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import toast, { Toaster } from "react-hot-toast";
import { CartProvider } from "./context/CartContext";
import TabTitleWatcher from "./Components/TabTitleWatcher";

export const metadata = {
  title: "Farmmerce Agriculture",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <meta name="google-site-verification" content="rszEqQis_kfUgJSnfECtDkudVyIW5GdWVkOhAAHmY7o" />
      <head>
        <title>Farmmerce Agriculture</title>
      </head>
      <body>
        <CartProvider>
          <TabTitleWatcher />
          {children}
        </CartProvider>{" "}
        <Toaster />
      </body>
    </html>
  );
}
